apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-observe-cockroachdb
  name: go-observe-cockroachdb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: go-observe-cockroachdb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: go-observe-cockroachdb
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: go-observe-cockroachdb
        ports:
        - name: http
          containerPort: 8090
        env:
        - name: PG_HOST
          value: cockroachdb-public
        - name: TRACE_HOST
          value: jaeger