apiVersion: v1
kind: Service
metadata:
  name: go-observe-cockroachdb
  labels:
    app: go-observe-cockroachdb
spec:
  type: ClusterIP
  ports:
  - port: 8090
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: go-observe-cockroachdb
