apiVersion: v1
kind: Service
metadata:
  labels:
    app: hotrod
  name: hotrod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: hotrod
  sessionAffinity: None
  type: ClusterIP