apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
  name: jaeger
spec:
  ports:
  - name: http
    port: 16686
    protocol: TCP
    targetPort: http
  - name: agent
    port: 6831
    protocol: UDP
    targetPort: agent
  - name: collector
    port: 14268
    protocol: TCP
    targetPort: collector
  - name: zipkin
    port: 9411
    protocol: TCP
    targetPort: zipkin
  selector:
    app: jaeger
  sessionAffinity: None
  type: ClusterIP


