apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        env:
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: '9411'
        ports:
        - name: agent
          containerPort: 6831
          protocol: UDP
        - name: http
          containerPort: 16686
          protocol: TCP
        - name: collector
          protocol: TCP
          containerPort: 14268
        - name: zipkin
          protocol: TCP
          containerPort: 9411